# Generated by Django 4.2.3 on 2023-09-14 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0003_alter_women_user_delete_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='women',
            name='user',
        ),
    ]
